todo: tipos array sarray2 array_eigen 

tipos:
	g++ main_tipos.cpp -Wall -O2 -o tipos

array:
	g++ main_array.cpp -Wall -O2 -o array
	
sarray2:
	g++ main_sarray2.cpp -Wall -O2 -o sarray2

array_eigen:
	g++ main_array_eigen.cpp -Wall -O2 -I /usr/include/eigen3 -o array_eigen